---
abstract: 'A Handy Debugging Module'
author:
  - 'Richard Kelsch <rich@rk-internet.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Debug-Easy
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper::Simple: '0'
  Log::Fast: '0'
  Term::ANSIColor: '4'
  Time::HiRes: '0'
  perl: '5.006'
version: 0.1
